version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Installing frontend dependencies..."
      - cd frontend
      - npm install
      - cd ..
      - echo "Installing backend dependencies..."
      - cd backend
      - npm install
      - cd ..
  build:
    commands:
      - echo "Building frontend..."
      - cd frontend
      - npm run build
      - cd ..
      - echo "Preparing backend bundle..."
      - cd backend
      # (optional) run tests here
      - zip -r ../backend.zip . -x "node_modules/*"
      - cd ..

artifacts:
  files:
    - frontend/build/**/*   # Only include the built frontend
  name: frontend.zip
  discard-paths: no
  secondary-artifacts:
    BackendArtifact:
      files:
        - backend.zip
      discard-paths: yes
