name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      CLOUDFRONT_DIST: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      EB_APP_NAME: aws-cloud-native-ecommerce
      EB_ENV_NAME: ecommerce-env

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # ------------------------------
      # FRONTEND DEPLOYMENT
      # ------------------------------
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install --legacy-peer-deps

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
        env:
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
          REACT_APP_STRIPE_PUBLISHABLE_KEY: ${{ secrets.REACT_APP_STRIPE_PUBLISHABLE_KEY }}

      - name: Deploy frontend to S3
        run: aws s3 sync frontend/build/ s3://$S3_BUCKET --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST --paths "/*"

      # ------------------------------
      # BACKEND DEPLOYMENT
      # ------------------------------
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install --legacy-peer-deps

      - name: Package backend for EB
        run: |
          cd backend
          zip -r ../backend-deploy.zip .

      - name: Upload backend bundle to S3
        run: aws s3 cp backend-deploy.zip s3://$S3_BUCKET/backend-deploy-${{ github.sha }}.zip

      - name: Deploy backend to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name $EB_APP_NAME \
            --version-label "build-${{ github.sha }}" \
            --source-bundle S3Bucket=$S3_BUCKET,S3Key=backend-deploy-${{ github.sha }}.zip

          aws elasticbeanstalk update-environment \
            --environment-name $EB_ENV_NAME \
            --version-label "build-${{ github.sha }}"
