name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install --legacy-peer-deps

      # 4. Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # 5. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 6. Deploy frontend to S3
      - name: Deploy frontend to S3
        run: |
          if [ -n "${S3_BUCKET}" ]; then
            aws s3 sync frontend/build/ s3://$S3_BUCKET --delete
          else
            echo "S3_BUCKET not defined, skipping deployment."
          fi
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}

      # 7. Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          if [ -n "${CLOUDFRONT_DIST}" ]; then
            aws cloudfront create-invalidation \
              --distribution-id $CLOUDFRONT_DIST \
              --paths "/*"
          else
            echo "CLOUDFRONT_DIST not defined, skipping invalidation."
          fi
        env:
          CLOUDFRONT_DIST: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
