name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      # 4. Run frontend tests
      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false

      # 5. Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # 6. Optional: Install backend dependencies if backend exists
      - name: Install backend dependencies
        run: |
          if [ -f "./backend/package-lock.json" ]; then
            echo "Installing backend dependencies..."
            cd backend
            npm ci
          else
            echo "No backend detected. Skipping backend installation."
          fi

      # 7. Optional: Run backend tests if backend exists
      - name: Run backend tests
        run: |
          if [ -f "./backend/package-lock.json" ]; then
            echo "Running backend tests..."
            cd backend
            npm test
          else
            echo "No backend detected. Skipping backend tests."
          fi
