name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # ------------------------------
      # FRONTEND CHECKS
      # ------------------------------
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install --legacy-peer-deps

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false || echo "No frontend tests"

      # ------------------------------
      # BACKEND CHECKS
      # ------------------------------
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install --legacy-peer-deps

      # Check if server compiles/starts without crashing
      - name: Lint backend
        working-directory: ./backend
        run: npm run lint || echo "No lint script"

      - name: Build backend
        working-directory: ./backend
        run: npm run build || echo "No backend build script"

      # Optional: run backend tests
      - name: Run backend tests
        working-directory: ./backend
        run: npm test -- --watchAll=false || echo "No backend tests"

      # Ensure backend starts successfully
      - name: Verify backend starts
        working-directory: ./backend
        run: |
          node server.js &
          sleep 5
          curl -f http://localhost:3000/api/products || (echo "Backend did not start correctly" && exit 1)
